# Generated by Django 5.0.6 on 2024-07-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='не указан', max_length=20),
        ),
        migrations.CreateModel(
            name='SpamServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_date', models.DateTimeField()),
                ('frequency', models.CharField(choices=[(1, 'Every Minute'), (5, 'Every 5 Minutes'), (15, 'Every 15 Minutes'), (30, 'Every 30 Minutes'), (60, 'Every Hour'), (1440, 'Daily')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed')], default='created', max_length=20)),
                ('clients', models.ManyToManyField(to='mailsender.client')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailsender.message')),
            ],
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('server_response', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailsender.spamservis')),
            ],
        ),
    ]
