# Generated by Django 5.0.6 on 2024-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0002_message_alter_client_comment_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamservis',
            name='frequency',
            field=models.CharField(choices=[('1', 'Every Minute'), ('5', 'Every 5 Minutes'), ('15', 'Every 15 Minutes'), ('30', 'Every 30 Minutes'), ('60', 'Every Hour'), ('1440', 'Daily')], max_length=20),
        ),
    ]
